default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_development

test:
  <<: *default
  database: hellorails_test

production:
  <<: *default
  database: hellorails_production
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
